require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.3.6
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
    - bin/*
    - spec/support/**/*

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - data/concerns/**/*
Metrics/MethodLength:
  Exclude:
    - db/**/*
    - app/services/sabre/**/*

  Max: 50

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 25
  Exclude:
    - db/migrate/*
Metrics/ClassLength:
  Exclude:
    - db/migrate/*
    - app/services/sabre/**/*

Layout/LineLength:
  Max: 140
  Exclude:
    - config/**/*

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/UnknownEnv:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*
Rails/BulkChangeTable:
  Enabled: false

Rails/HttpPositionalArguments:
  Exclude:
    - spec/acceptance/v1/interviews_spec.rb
    - spec/acceptance/v1/users/interviews_spec.rb

RSpec/NestedGroups:
  Max: 5


Style/OpenStructUse:
  Enabled: false