name: Checks

on:
  pull_request:
    branches:
      - dev

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
          cache-version: 1
      - name: Run rubocop
        run: |
          bundle exec rubocop
  rspec:
    needs: rubocop
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.10
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
          POSTGRES_DB: drvn_test
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7.0
        ports:
          - 6379:6379
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://test:password@localhost:5432/drvn_test
      USE_STATIC_ASSETS: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Prepare config
        run: |
          cp config/credentials/test.key.sample config/credentials/test.key
          cp config/credentials/test.yml.enc.sample config/credentials/test.yml.enc
      - name: Run tests
        run: |
          bundle exec rspec ./spec -f j -o tmp/rspec_results.json -f p